title: "Death and life of ‘operative history’"
email: palazzo@unb.br
description: >-
  The Italian debates of the post-war era regarding the possibility of
  an 'operative' history of architecture, revolving around Manfredo
  Tafuri's critique of Saverio Muratori's method of procedural typology
  and his ambiguous stance on Aldo Rossi's later work, provide the
  theoretical background for a present-day 'Italian school' of
  typo-morphology. This 'school' is split between the modernist
  disciples of Muratori and the younger traditionalists, loosely
  inspired by Rossi. The points of agreement and of disagreement within
  this school point to a continued reevaluation of Tafuri's call for a
  critical and autonomous historiography, although the theoretical
  pitfalls of giving an operative role to historical knowledge are ever
  present.
baseurl: "/tipo_ecletismo"
url: "https://dmcpatrimonio.github.io"
twitter_username: p3palazzo
github_username:  p3palazzo

# Build settings {{{1
theme: tufte-pandoc-jekyll
markdown: Pandoc
pandoc:
  extensions:
    - defaults: "_spec/defaults.yaml"
    - section-divs
plugins:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-pandoc
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - LICENSE
  - Makefile
keep_files:
  - ".git"
