source "https://rubygems.org"
gem "jekyll", "~>4.2"
gem "webrick"
group :jekyll_plugins do
  gem "jekyll-coffeescript"
  gem "jekyll-feed"
  gem "jekyll-optional-front-matter"
  gem "jekyll-paginate"
  gem "jekyll-pandoc"
  gem "jekyll-relative-links"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "sassc"
  gem "stringex"
  gem "tufte-pandoc-jekyll"
end
